<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-LinkShortener-d1dfe533-2627-444c-b276-f62bb454d981</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LinkShortener.Data\LinkShortener.Data.csproj" />
    <ProjectReference Include="..\LinkShortener.Client\LinkShortener.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.12" />
  </ItemGroup>

</Project>
