// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultitenantApp.Data;

#nullable disable

namespace MultitenantApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultitenantApp.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Product");

                    b
                        .UseTphMappingStrategy()
                        .HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("MultitenantApp.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jay",
                            Surname = "Garrick"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Barry",
                            Surname = "Allen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wally",
                            Surname = "West"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bart",
                            Surname = "Allen"
                        });
                });

            modelBuilder.Entity("MultitenantApp.Data.SeedProduct", b =>
                {
                    b.HasBaseType("MultitenantApp.Data.Product");

                    b.HasDiscriminator().HasValue("SeedProduct");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "iPhone",
                            TenantId = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MacBook",
                            TenantId = "1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Galaxy S21",
                            TenantId = "2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Galaxy Tab",
                            TenantId = "2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
